package:
  name: suitesparse
  version: 4.4.1

requirements:
  build:
    - cmake  # [win]
    - openblas 0.2.13  # [win]
    - metis 5.1.0

  run:
    - metis 5.1.0
    - openblas 0.2.13  # [win]

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: GPLv3
