package:
  name: suitesparse
  version: 4.4.1

requirements:
  build:
    - cmake [win]
    - metis 5.1.0
  run:
    - metis 5.1.0

about:
  home: http://faculty.cse.tamu.edu/davis/suitesparse.html
  license: GPLv3
